Repository tmax-cloud/cd-operator, pull requests merged in 2021-09, with the labels that each got.

#2 [feat] Set up the cd-operator
  Makefile
  PROJECT
  api/v1/application_types.go
  api/v1/git_types.go
  api/v1/zz_generated.deepcopy.go
  build/controller/Dockerfile
  cmd/controller/main.go
  config/controller/controller.yaml
  config/crd/bases/cd.tmax.io_applications.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_gits.yaml
  config/crd/patches/webhook_in_gits.yaml
  config/rbac/git_editor_role.yaml
  config/rbac/git_viewer_role.yaml
  config/samples/cd_v1_git.yaml
  config/samples/kustomization.yaml
  controllers/application_controller.go
  go.mod
  go.sum
  internal/apiserver/apiserver.go
  internal/apiserver/authorize.go
  internal/logrotate/logrotate.go
  internal/utils/k8s.go
  internal/utils/rand.go
  internal/utils/response.go
  internal/utils/utils.go
  internal/utils/utils_test.go
  internal/wrapper/wrapper.go
Labels: size/XXL

#3 [build] Fix makefile
  Makefile
Labels: size/XS

#4 [bugfix] Fix rbac yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  controllers/application_controller.go
  go.mod
  pkg/manifestmanager/manifestmanager.go
Labels: size/M

#5 [feat] Implement GetManifestURL
  api/v1/application_types.go
  config/crd/bases/cd.tmax.io_applications.yaml
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
Labels: size/L

#8 [feat] Implement ApplyManifest
  go.mod
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
Labels: size/M

#14 feat/crd_refactoring
  api/v1/application_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/cd.tmax.io_applications.yaml
  go.mod
  go.sum
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
Labels: size/L

#15 [feat] Implement GetCitClient for server pkg
  api/v1/application_types.go
  config/rbac/role.yaml
  controllers/application_controller.go
  internal/utils/utils.go
  internal/utils/utils_test.go
  pkg/server/handler_webhook.go
  pkg/server/plugin.go
  pkg/server/server.go
Labels: size/L

#16 [feat] Implement management of Resources
  api/v1/deployresource_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/cd.tmax.io_deployresources.yaml
  config/crd/kustomization.yaml
  controllers/suite_test.go
  go.mod
  go.sum
  internal/wrapper/wrapper.go
  pkg/git/github/github.go
  pkg/git/gitlab/gitlab.go
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
  pkg/server/server.go
Labels: size/L

#17 [feat] Support Multiple Plain Yaml File
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
Labels: size/L

#20 [chore] Apply Multi Manifests
  pkg/dispatcher/dispatcher.go
Labels: size/XS

#22 [chore] Bump version to v0.0.1
  Makefile
  config/cd-webhook.yaml
  config/controller/controller.yaml
  config/rbac/role_binding.yaml
  config/release.yaml
  hack/release-manifest.sh
Labels: size/L, approved

#23 [fix] fix typo
  config/controller/controller.yaml
  config/release.yaml
Labels: size/XS, approved

#24 [ci] Add IntegrationConfig file
  ci.yaml
Labels: size/L, approved

#25 [docs] Add guide for installation
  README.md
  docs/README.md
  docs/installation.md
Labels: approved, size/S

#26 [feat] Implement to register webhook automatically
  api/v1/application_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/cd.tmax.io_applications.yaml
  controllers/application_controller.go
  go.mod
  go.sum
  internal/utils/utils.go
Labels: size/L, approved
