Repository tmax-cloud/cd-operator, pull requests merged in 2021-10, with the labels that each got.

#34 [fix] Fix the error that occur when already existing resources are
  api/v1/deployresource_types.go
  config/crd/bases/cd.tmax.io_deployresources.yaml
  go.mod
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
Labels: size/L, approved

#35 [fix] fix scheme error
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
Labels: size/M, approved

#37 [fix] Fix the 'recursivePathCheck' error
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
Labels: size/M, approved

#40 [feat] Implement Application Destination
  api/v1/application_types.go
  api/v1/deployresource_types.go
  config/crd/bases/cd.tmax.io_applications.yaml
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
Labels: size/L, approved

#42 [feat] Use expose & configmap controller
  api/v1/application_types.go
  cmd/controller/main.go
  config/controller/controller.yaml
  config/rbac/role.yaml
  config/release.yaml
  controllers/configmap_controller.go
  controllers/expose_controller.go
  go.mod
  go.sum
  internal/configs/configs.go
  internal/configs/controller.go
  internal/utils/restclient.go
Labels: size/XXL, approved

#43 [feat] Add application sync API
  api/v1/application_types.go
  cmd/controller/main.go
  config/apiservice/apiservice.yaml
  config/cd-webhook.yaml
  config/rbac/role.yaml
  config/release.yaml
  controllers/application_controller.go
  go.mod
  go.sum
  internal/apiserver/apiserver.go
  pkg/apiserver/apis/apis.go
  pkg/apiserver/apis/v1/applications/applications.go
  pkg/apiserver/apis/v1/applications/deploy.go
  pkg/apiserver/apis/v1/v1.go
  pkg/apiserver/cert.go
  pkg/apiserver/server.go
Labels: size/XXL, approved

#47 [fix] Fix checkSync condition
  config/release.yaml
  controllers/application_controller.go
  pkg/dispatcher/dispatcher.go
Labels: size/M, approved

#49 [feat] Manage deploy resource
  api/v1/deployresource_types.go
  config/crd/bases/cd.tmax.io_deployresources.yaml
  config/release.yaml
  controllers/application_controller.go
  go.sum
  pkg/manifestmanager/deployresource.go
  pkg/manifestmanager/manifestmanager.go
  pkg/sync/sync.go
Labels: size/L, approved
