Repository tmax-cloud/cd-operator, pull requests merged in 2021-11, with the labels that each got.

#53 [test] Add manifestmanager test codes
  pkg/apiserver/apis/v1/applications/deploy.go
  pkg/httpclient/httpclient.go
  pkg/httpclient/mock.go
  pkg/manifestmanager/deployresource_test.go
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
  pkg/sync/sync.go
Labels: approved, size/XL

#54 [feat] Implement to install helm chart
  config/crd/bases/cd.tmax.io_applications.yaml
  config/crd/bases/cd.tmax.io_deployresources.yaml
  go.mod
  go.sum
  util/helmclient/client.go
  util/helmclient/client_test.go
Labels: approved, size/XL

#55 [feat] Support 'InstallHelmChart' and 'GitRepoClone' in Manifestmanager
  api/v1/application_types.go
  api/v1/zz_generated.deepcopy.go
  build/controller/Dockerfile
  config/crd/bases/cd.tmax.io_applications.yaml
  go.mod
  go.sum
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
  util/gitclient/client.go
  util/gitclient/client_test.go
  util/helmclient/client.go
  util/helmclient/client_test.go
Labels: size/L, approved

#56 test/helm_manifest
  go.mod
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
Labels: size/M, approved

#57 [test] Add test code for InstallHelmChart
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
Labels: size/M, approved

#58 [feat] Use manifest manager interface
  api/v1/application_types.go
  config/crd/bases/cd.tmax.io_applications.yaml
  config/release.yaml
  controllers/application_controller.go
  pkg/apiserver/apis/v1/applications/deploy.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/manifestmanager/deployresource.go
  pkg/manifestmanager/deployresource_test.go
  pkg/manifestmanager/helm.go
  pkg/manifestmanager/helm_test.go
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
  pkg/manifestmanager/plainyaml.go
  pkg/manifestmanager/plainyaml_test.go
  pkg/sync/sync.go
Labels: size/XXL, approved

#60 [feat] Add Helm sync status check
  controllers/application_controller.go
  pkg/manifestmanager/helm.go
  pkg/manifestmanager/helm_test.go
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/manifestmanager_test.go
  pkg/manifestmanager/plainyaml.go
  pkg/manifestmanager/plainyaml_test.go
  pkg/sync/sync.go
  util/helmclient/client.go
  util/helmclient/client_test.go
Labels: size/XXL, approved

#62 [fix] Set target client by kubeconfig value data
  go.mod
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/manifestmanager/helm.go
  pkg/manifestmanager/plainyaml.go
  pkg/manifestmanager/plainyaml_test.go
Labels: size/L, approved

#64 [bugfix] Fix the issue that Status.Conditions.Message and Reason are Invalid
  config/release.yaml
  controllers/application_controller.go
Labels: approved, size/S

#67 [chore] Clarify plain yaml sync status
  controllers/application_controller.go
  pkg/manifestmanager/plainyaml.go
  pkg/manifestmanager/plainyaml_test.go
  pkg/sync/sync.go
Labels: size/M, approved

#68 [fix] Fix reconciler errors
  controllers/application_controller.go
Labels: size/M, approved

#70 [feat] Implement InstallChartByCLI and UninstallReleaseByCLI
  util/exec/exec.go
  util/exec/exec_test.go
  util/helmclient/client.go
  util/helmclient/client_test.go
Labels: size/L, approved

#71 [chore] Networking.v1beta1 -> v1
  controllers/expose_controller.go
Labels: size/XS, approved

#72 [bugfix] Fix that Resources are always deployed in "default" namespace
  pkg/manifestmanager/helm.go
  util/helmclient/client_test.go
Labels: size/XS, approved

#73 [feat] Add GetManifestUrl method to git interface
  controllers/application_controller.go
  pkg/git/fake/fake.go
  pkg/git/git.go
  pkg/git/git_types.go
  pkg/git/github/github.go
  pkg/git/gitlab/gitlab.go
  pkg/manifestmanager/helm.go
  pkg/manifestmanager/plainyaml.go
  pkg/manifestmanager/plainyaml_test.go
  pkg/sync/sync.go
Labels: size/L, approved

#74 [fead] Add Open, Fetch and Pull methods for helm sync
  pkg/manifestmanager/helm.go
  util/gitclient/client.go
  util/gitclient/client_test.go
  util/helmclient/client_test.go
Labels: size/L, approved

#75 [refactor] Handle manifests by git client
  controllers/application_controller.go
  pkg/git/fake/fake.go
  pkg/git/git.go
  pkg/git/git_types.go
  pkg/git/github/github.go
  pkg/git/github/github_types.go
  pkg/git/gitlab/gitlab.go
  pkg/git/gitlab/gitlab_types.go
  pkg/manifestmanager/helm.go
  pkg/manifestmanager/manifestmanager.go
  pkg/manifestmanager/plainyaml.go
  pkg/manifestmanager/plainyaml_test.go
  pkg/manifestmanager/utils/util_test.go
  pkg/manifestmanager/utils/utils.go
Labels: approved, size/XL

#76 [feat] Make git repository cloned only once for helm sync
  controllers/application_controller.go
  pkg/manifestmanager/helm.go
Labels: size/M, approved
